# Generated by Django 5.1.7 on 2025-03-12 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlackList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refesh', models.CharField(blank=True, max_length=100, unique=True)),
            ],
        ),
    ]
