# Generated by Django 5.1.7 on 2025-03-12 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlackList',
        ),
    ]
