# Generated by Django 5.1.7 on 2025-03-14 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bugs', '0001_initial'),
        ('project', '0007_project_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('note_bugs', models.ManyToManyField(blank=True, related_name='Note_of_bugs', to='bugs.bugs')),
                ('note_project', models.ManyToManyField(blank=True, related_name='Note_of_project', to='project.project')),
            ],
            options={
                'verbose_name': 'Note',
                'db_table': 'note',
                'ordering': ('-created_at',),
            },
        ),
    ]
