# Generated by Django 5.1.7 on 2025-03-14 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='note_bugs',
            new_name='bugs',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='note_project',
            new_name='project',
        ),
    ]
