# Generated by Django 5.1.7 on 2025-03-14 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0002_rename_project_bugs_bugs_project'),
        ('note', '0002_rename_note_bugs_note_bugs_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='project',
        ),
        migrations.AlterField(
            model_name='note',
            name='bugs',
            field=models.ManyToManyField(blank=True, null=True, related_name='Note_of_bugs', to='bugs.bugs'),
        ),
    ]
