# Generated by Django 5.1.7 on 2025-03-17 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0002_rename_project_bugs_bugs_project'),
        ('note', '0003_remove_note_project_alter_note_bugs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='bugs',
            field=models.ManyToManyField(blank=True, related_name='Note_of_bugs', to='bugs.bugs'),
        ),
    ]
