# Generated by Django 5.1.7 on 2025-03-19 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0004_alter_bugs_priority_alter_bugs_status'),
        ('note', '0004_alter_note_bugs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='bugs',
            field=models.ManyToManyField(blank=True, related_name='note', to='bugs.bugs'),
        ),
    ]
