# Generated by Django 5.1.7 on 2025-03-10 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_authuser_options_alter_authuser_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authuser',
            options={},
        ),
        migrations.AlterModelManagers(
            name='authuser',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='authuser',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='authuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='authuser',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='authuser',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='authuser',
            name='user_permissions',
        ),
        migrations.AlterField(
            model_name='authuser',
            name='username',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
