# Generated by Django 5.1.7 on 2025-03-10 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_authuser_options_alter_authuser_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='authuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='email',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
