# Generated by Django 5.1.7 on 2025-03-10 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_authuser_is_staff_alter_authuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authuser',
            name='email',
            field=models.EmailField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='username',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
