# Generated by Django 5.1.7 on 2025-03-14 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
