# Generated by Django 5.1.7 on 2025-03-14 05:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_alter_user_table'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Project', max_length=255)),
                ('description', models.CharField(blank=True, max_length=512)),
                ('status', models.CharField(choices=[('open', 'Open'), ('close', 'Close')], default='open', max_length=50)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project_member', models.ManyToManyField(blank=True, related_name='member_of_project', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Project',
                'db_table': 'project',
                'ordering': ('-created_at',),
            },
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
