# Generated by Django 5.1.7 on 2025-03-17 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_alter_project_ower_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='ower_by',
            new_name='owner_by',
        ),
    ]
