# Generated by Django 5.1.7 on 2025-03-14 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0007_project_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bugs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Project', max_length=255)),
                ('description', models.CharField(blank=True, max_length=512)),
                ('status', models.CharField(choices=[('open', 'Open'), ('close', 'Close')], default='open', max_length=50)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project_bugs', models.ManyToManyField(blank=True, related_name='Bugs_of_project', to='project.project')),
            ],
            options={
                'verbose_name': 'Bugs',
                'db_table': 'bugs',
                'ordering': ('-created_at',),
            },
        ),
    ]
