# Generated by Django 5.1.7 on 2025-03-14 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bugs',
            old_name='project_bugs',
            new_name='project',
        ),
    ]
