# Generated by Django 5.1.7 on 2025-03-19 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0002_rename_project_bugs_bugs_project'),
        ('project', '0013_alter_project_owner_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugs',
            name='project',
            field=models.ManyToManyField(blank=True, related_name='bugs', to='project.project'),
        ),
    ]
